defaults:
- _self_
- override hydra_logging: none  
- override job_logging: none

run:
  dir: .

output_subdir: null

job:
    env_set:
        # In case wandb process interferes with
        # hydra's multi-launcher
        WANDB_START_METHOD: thread