# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# PROJECT_ROOT is inferred and set by pyrootutils package in `train.py` and `eval.py`
root_dir: ${oc.env:PROJECT_ROOT}

# path to data directory
data_dir: ${paths.root_dir}/data
data_not_mounted_dir: ${paths.root_dir}/data_not_mounted
precreated_datasets_dir: ${paths.root_dir}/precreated_datasets

# path to pretrained checkpoints
pretrained_checkpoints_dir:  ${paths.root_dir}/pretrained_checkpoints

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${paths.root_dir}/experiments

# path to working directory
work_dir: ${hydra:runtime.cwd}