_target_: src.datamodules.thumos_datamodules.ThumosImagesDataModule

defaults:
  - _self_
  - dataset_info: thumos_data-featurescaptions_fps-24_frames-16_swstride-6 #thumosbaseball_data-featurescaptions_fps-24_frames-16_swstride-6 #thumos_data-featurescaptions_fps-24_frames-16_swstride-6

datasets:
  
  # Actually the valid dataset for Thumos  
  train_dataset:
    _target_: src.datamodules.datasets.untrimmed_fullvideos_features_captions_dataset.UntrimmedFullVideosFeaturesCaptionsDataset
    data_root_path: ${paths.data_not_mounted_dir}
    random_start_idx: False    
    latest_start_idx_videos: 0.0 # in percentage of video length
    shuffle_on_load: True


  # Actually the test dataset for Thumos  
  valid_dataset:
    _target_: src.datamodules.datasets.untrimmed_fullvideos_features_dataset.UntrimmedFullVideosFeaturesDataset
    data_root_path: ${paths.data_not_mounted_dir}
    random_start_idx: False    
    latest_start_idx_videos: None # in percentage of video length
    shuffle_on_load: False

loaders:

  train_loader:
    batch_size: 1
    shuffle: True
    num_workers: 0
    drop_last: False
    pin_memory: True

  valid_loader:
    batch_size: 1
    shuffle: False
    num_workers: 0
    drop_last: False
    pin_memory: True

  # predict_loader:
  #   batch_size: 1
  #   shuffle: False
  #   num_workers: 0
  #   drop_last: False
  #   pin_memory: False

transforms: 
  train_transforms: None
  valid_transforms: None