dataset_name: thumos

modality: images
train_images_dirname: frames/validation/
valid_images_dirname: frames/test/
#target_dirname: data_not_mounted/DATA-thumos-corrected-labels/BaseballPitch
target_dirname: data/thumos/target_perframe/
captions_dirname: data_not_mounted/DATA-thumos-perfeature-captions/BaseballPitch/

train_video_names: ["video_validation_0000266", "video_validation_0000681", "video_validation_0000682", "video_validation_0000683", "video_validation_0000684", 
                    "video_validation_0000685", "video_validation_0000686", "video_validation_0000687", "video_validation_0000688", "video_validation_0000689", "video_validation_0000690"]


valid_video_names: ["video_test_0000324", "video_test_0000664", "video_test_0000714", "video_test_0000767", "video_test_0000873", "video_test_0000946", "video_test_0000964",
                    "video_test_0001038", "video_test_0001182", "video_test_0001324", "video_test_0001447"]

video_fps: 24
image_size: [3,180,320]
images_per_feature: 16
sliding_window_stride: 6
feature_fps: 4
train_videos_mean: [0.3345, 0.3322, 0.3071]
train_videos_std: [0.3023, 0.2974, 0.2910]


class_names: ["Background", "BaseballPitch", "BasketballDunk", "Billiards", "CleanAndJerk", "CliffDiving", "CricketBowling", "CricketShot", "Diving", "FrisbeeCatch", "GolfSwing", "HammerThrow", "HighJump", "JavelinThrow", "LongJump", "PoleVault", "Shotput", "SoccerPenalty", "TennisSwing", "ThrowDiscus", "VolleyballSpiking", "Ambiguous"]
num_classes: 22
ignore_index: 21
background_index: 0